apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: mock
  name: mock
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: mock
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: mock
    spec:
      containers:
        - image: gcr.io/bright-sunlight-227912/mock:latest
          imagePullPolicy: Always
          name: mock
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            initialDelaySeconds: 120
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Authorization
                  value: Basic ZGVtbzpkZW1v
          livenessProbe:
            initialDelaySeconds: 120
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Authorization
                  value: Basic ZGVtbzpkZW1v
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30