---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mock-service"
  namespace: "default"
  labels:
    run: "mock"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    run: "mock"
  type: "LoadBalancer"
  loadBalancerIP: ""